### ISSUE TITLE
IPH Crashing after setting up fit for Raitaru

### ISSUE THREAD

**Issue by SupCMDr** [EVEIPH/EVE-IPH#103]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System?  Win10
What tab or screen did the error occur? Citadel/EC Fitting window
What are the steps to reproduce the Error? Unsure.  IPH is now crashing with the same error on start-up.
Web link to a screenshot of your error: N/A
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: Specified cast is not valid.
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Specified cast is not valid. ---> System.InvalidCastException: Specified cast is not valid.
   at System.Data.SQLite.SQLiteDataReader.VerifyType(Int32 i, DbType typ)
   at System.Data.SQLite.SQLiteDataReader.GetDouble(Int32 i)
   at EVE_Isk_per_Hour.ManufacturingFacility.DisplayFacilityBonus(ProductionType BuildType, Int32 ItemGroupID, Int32 ItemCategoryID, String Activity, FacilityTypes FacilityType, String FacilityName)
   at EVE_Isk_per_Hour.ManufacturingFacility.LoadFacilities(Boolean NewFacility, String& FacilityActivity, Boolean& AutoLoadFacility, String OverrideFacilityName)
   at EVE_Isk_per_Hour.ManufacturingFacility.LoadFacility(Int32 ItemGroupID, Int32 ItemCategoryID, Int32 BlueprintTech, Boolean BPHasComponents, Boolean LoadDefault, IndustryFacility DefaultFacility, Boolean ComboSelect)
   at EVE_Isk_per_Hour.ManufacturingFacility.InitializeFacilities(FacilityView ViewType, ProductionType InitialProductionType)
   at EVE_Isk_per_Hour.ManufacturingFacility.InitializeControl(FacilityView ViewType, Int64 SentSelectedCharacterID, ProgramLocation FormLocation, ProductionType InitialProductionType)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking:

**Comment by Zifrian** [comment]
Email me the fitting you stored and where and I'll try and see if I can get it to throw the error.

**Comment by SupCMDr** [comment]
Sorry for not getting back to you earlier.  I don't exactly recall offhand what i had picked for the fitting in that particular case.  I do know I was messing around with a Raitaru, Invention + Manufacturing service modules, and some of the T1 rigs.   Don't recall which exact configuration was used when the crash occurred.

**Comment by Zifrian** [comment]
OK, let me know if it comes up again and I'll re-open.
