### ISSUE TITLE
ESI 420 error on initial startup

### ISSUE THREAD

**Issue by jeff4747** [EVEIPH/EVE-IPH#104]
- Install IPH on Windows 10 (D:\Program Files (x86)\EVE IPH)
- Start IPH.  Let updater apply update.
- Login with ESI screen appears.  Click login button, and log in using browser
- "Page is not working" error in browser, IPH says character successfully added.
- Click "Set Default" in IPH. Receive a bunch of HTTP 420 errors from IPH
- IPH crashes

An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

Source: EVE Isk per Hour
Message: Object reference not set to an instance of an object.
Raw Error Text: System.NullReferenceException: Object reference not set to an instance of an object.
   at EVE_Isk_per_Hour.EVENPCStandings.UpdateCharacterStandings(Int64 ID, SavedTokenData CharacterTokenData)
   at EVE_Isk_per_Hour.EVENPCStandings.LoadCharacterStandings(Int64 CharacterID, SavedTokenData CharacterTokenData)
   at EVE_Isk_per_Hour.Character.LoadCharacterData(Int64 CharacterID, SavedTokenData& TokenData, Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Character.LoadDefaultCharacter(Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Public_Variables.LoadSelectedCharacter(String CharacterName, Boolean PlaySound)
   at EVE_Isk_per_Hour.frmSetCharacterDefault.btnSelectDefault_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
Closing. Reopen if the error still exists.
