### ISSUE TITLE
IPH crash when attempting to set structure fitting

### ISSUE THREAD

**Issue by UNKNOWN314159** [EVEIPH/EVE-IPH#115]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

What is your Operating System? 
- Win7 Pro x64

What tab or screen did the error occur? 
- Blueprint tab, just clicked the fitting button to modify structure fit

What are the steps to reproduce the Error? 
- Choose Strip Miner I BP, change region/system and go to modify structure fitting

Source: EVE Isk per Hour
Message: Object reference not set to an instance of an object.
Raw Error Text: System.NullReferenceException: Object reference not set to an instance of an object.
   at EVE_Isk_per_Hour.frmUpwellStructureFitting.LoadUpwellStuctureStats(Boolean IgnoreLabelUpdate)
   at EVE_Isk_per_Hour.frmUpwellStructureFitting.LoadStructure(String SentUSName)
   at EVE_Isk_per_Hour.frmUpwellStructureFitting..ctor(String InitUSName, Int64 CharacterID, ProductionType ProductionTypeCode, FacilityView FacilityLocation, String FacilitySystem)
   at EVE_Isk_per_Hour.ManufacturingFacility.btnFacilityFitting_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by UNKNOWN314159** [comment]
Upon further investigation, I had forgotten to select a structure type after setting the new region/system and I clicked the "Fitting" button. If you select a structure from the dropdown, the program works as expected.

**Comment by Zifrian** [comment]
Turns out you shouldn't be able to do this. I was able to get it to crash when deleting the text from the combo and then selecting a new system. I'll fix this in the next update.

Thanks
