### ISSUE TITLE
Unhandled Error

### ISSUE THREAD

**Issue by Varaxian** [EVEIPH/EVE-IPH#118]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Win 10
What tab or screen did the error occur? Manufacturing List
What are the steps to reproduce the Error? Ships, Drones, Modules, Preview, Calculate
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: Arithmetic operation resulted in an overflow.
Raw Error Text: System.OverflowException: Arithmetic operation resulted in an overflow.
   at EVE_Isk_per_Hour.Public_Variables.ConvertDHMSTimetoSeconds(String SentTime)
   at EVE_Isk_per_Hour.frmMain.InsertManufacturingItem(ManufacturingItem SentItem, Double SVRThreshold, Boolean InsertBlankSVR, List`1& SentList, List`1& FormatList)
   at EVE_Isk_per_Hour.frmMain.DisplayManufacturingResults(Boolean Calculate)
   at EVE_Isk_per_Hour.frmMain.btnCalculate_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
Can you send me / post a screenshot of your manufacturing tab settings? It’s an issue with one of the settings.

**Comment by Zifrian** [comment]
Without a screenshot, I can't debug this. Send it to ZifrianEVE@gmail.com if you don't want to share openly.

Closing without more info.
