### ISSUE TITLE
Unhandled error in application settings

### ISSUE THREAD

**Issue by Eclypx** [EVEIPH/EVE-IPH#119]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10
What tab or screen did the error occur? Application settings
What are the steps to reproduce the Error? New install, open settings, select "disable sound" checkbox, hit save
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: Object reference not set to an instance of an object.
Raw Error Text: System.NullReferenceException: Object reference not set to an instance of an object.
   at EVE_Isk_per_Hour.frmSettings.btnSave_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
Does this happen when only selecting 'disable sound' or other options? I have a feeling it has something to do with your account, which I do some work with behind the scenes. Let me know and a screenshot would be helpful. Thanks

**Comment by Zifrian** [comment]
Closing without more information.
