### ISSUE TITLE
Unhandled error when starting

### ISSUE THREAD

**Issue by baczoni** [EVEIPH/EVE-IPH#140]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10 X64
What tab or screen did the error occur?  on Launch
What are the steps to reproduce the Error? Launch the application
Web link to a screenshot of your error:  https://snag.gy/liTDGv.jpg
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E) ---> System.DllNotFoundException: Unable to load DLL 'SQLite.Interop.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SQLite.UnsafeNativeMethods.sqlite3_config_none(SQLiteConfigOpsEnum op)
   at System.Data.SQLite.SQLite3.StaticIsInitialized()
   at System.Data.SQLite.SQLiteLog.Initialize(String className)
   at System.Data.SQLite.SQLiteConnection..ctor(String connectionString, Boolean parseViaFramework)
   at System.Data.SQLite.SQLiteConnection..ctor()
   at EVE_Isk_per_Hour.DBConnection..ctor(String DBFileName)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking:

**Comment by baczoni** [comment]
Nvr mind, read the patch notes. Needed to run the application as Admin to be able to finish the update correctly.
