### ISSUE TITLE
Whenever I try to update prices from a certain structure with the "Add structure ID" function it gives me this error.

### ISSUE THREAD

**Issue by Sclify** [EVEIPH/EVE-IPH#143]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Win 7
What tab or screen did the error occur? After opening the app when trying to pull prices from a structure.
What are the steps to reproduce the Error? Open the app, click the update prices tab, click add structure ids, insert your structure to pull from, either clicking check ID or Save structure will generate this error.
Web link to a screenshot of your error: https://imgur.com/a/CMyRPQ7
In addition to a screenshot, copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: Conversion from string "1022734985679 alt='Current Stati" to type 'Long' is not valid.
Raw Error Text: System.InvalidCastException: Conversion from string "1022734985679 alt='Current Stati" to type 'Long' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDecimal(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToLong(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToLong(String Value)
   at EVE_Isk_per_Hour.frmAddStructureIDs.CheckIDforMarketData(Int32 Index)
   at EVE_Isk_per_Hour.frmAddStructureIDs.Button_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
I'm not sure how you are getting that formatted text. Did you use the instructions on the add structure ID?

**Comment by jamesemullican** [comment]
I have not added any structure ID's.

I changed the 'Price Setting' from 'Single Select' to 'Price Profile'. Then I used the 'Set Defaults:'. Then hit Download Prices. And, I get the unhandled error.
