### ISSUE TITLE
Unhandled Exception when typing into the "selected blueprint or reaction" bar

### ISSUE THREAD

**Issue by Lucifirius** [EVEIPH/EVE-IPH#149]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Win10
What tab or screen did the error occur? Blueprints
What are the steps to reproduce the Error? Type into "Selected Blueprint or Reaction" while selecting Reactions
Web link to a screenshot of your error: https://i.vgy.me/IdLEll.png
In addition to a screenshot, copy the data below and send to developer.

Source: System.Data.SQLite
Message: SQL logic error
no such column: IT2.marketGroupID
Raw Error Text: code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
no such column: IT2.marketGroupID
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader()
   at EVE_Isk_per_Hour.frmMain.GetBPWithName(String bpName)
   at EVE_Isk_per_Hour.frmMain.cmbBPBlueprintSelection_TextChanged(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.OnTextChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
This should be fixed now.
