### ISSUE TITLE
Price Profile unhandled exception error

### ISSUE THREAD

**Issue by jamesemullican** [EVEIPH/EVE-IPH#150]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10

What tab or screen did the error occur? Update Prices - Pressed 'Download Prices"

What are the steps to reproduce the Error? Price Profile: RawMaterials- MinSell-Jita, Manf.Items-Max Buy-TheForge-All systems

Web link to a screenshot of your error: 

https://imgur.com/hQecQwB

In addition to a screenshot, copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: Conversion from string "" to type 'Long' is not valid.
Raw Error Text: System.InvalidCastException: Conversion from string "" to type 'Long' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDecimal(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToLong(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToLong(String Value)
   at EVE_Isk_per_Hour.MarketPriceInterface.UpdateESIMarketOrders(List`1 CacheItems)
   at EVE_Isk_per_Hour.frmMain.LoadPrices(List`1 SentItems)
   at EVE_Isk_per_Hour.frmMain.btnImportPrices_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
This should be fixed in the current version.
