### ISSUE TITLE
Unhandled Exception changing market price to empty string

### ISSUE THREAD

**Issue by ASB2** [EVEIPH/EVE-IPH#151]
Was attempting to zero out the market price in the blueprints tab, pressed enter without inputting anything and the program crashed

An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? 
What tab or screen did the error occur? 
What are the steps to reproduce the Error? 
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: Microsoft.VisualBasic
Message: Conversion from string "" to type 'Double' is not valid.
Raw Error Text: System.InvalidCastException: Conversion from string "" to type 'Double' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToDouble(String Value)
   at EVE_Isk_per_Hour.frmMain.UpdateMarketPriceManually()
   at EVE_Isk_per_Hour.frmMain.txtBPMarketPriceEdit_KeyDown(Object sender, KeyEventArgs e)
   at System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   at System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   at System.Windows.Forms.Control.ProcessKeyMessage(Message& m)
   at System.Windows.Forms.Control.WmKeyChar(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.TextBoxBase.WndProc(Message& m)
   at System.Windows.Forms.TextBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
This is fixed in Build 4.0.7484.40109
