### ISSUE TITLE
`Attempt to write a readonly database`

### ISSUE THREAD

**Issue by hoangphucITJP** [EVEIPH/EVE-IPH#170]
I encounter this error. But if I run the app as administrator, it works normally.

What is your Operating System? 
- **Windows 10**

What tab or screen did the error occur? 
- **Right after the Initializing database splash screen**

What are the steps to reproduce the Error? 
- **Just open the app and it happens**

```
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? 
What tab or screen did the error occur? 
What are the steps to reproduce the Error? 
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: attempt to write a readonly database
attempt to write a readonly database
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: attempt to write a readonly database
attempt to write a readonly database ---> System.Data.SQLite.SQLiteException: attempt to write a readonly database
attempt to write a readonly database
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at EVE_Isk_per_Hour.DBConnection.ExecuteNonQuerySQL(String SQL)
   at EVE_Isk_per_Hour.DBConnection..ctor(String DBFileName)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking: PRAGMA auto_vacuum = FULL; PRAGMA synchronous = NORMAL; PRAGMA locking_mode = NORMAL; PRAGMA cache_size = 10000; PRAGMA page_size = 4096; PRAGMA temp_store = DEFAULT; PRAGMA journal_mode = WAL; PRAGMA count_changes = OFF
```

**Comment by Zifrian** [comment]
Added a bit more logic for this to catch this error. Closing for now.
