### ISSUE TITLE
Missing default for price modifiers

### ISSUE THREAD

**Issue by rsfutch77** [EVEIPH/EVE-IPH#178]
Right after an update, there are no defaults for my price modifier dropdowns. Downloading prices causes this crash.
Setting the modifiers to anything other than blank resolves the issue. 

![image](https://user-images.githubusercontent.com/26337219/176380710-9706b929-a99a-40fd-b130-5d7ee4dc004c.png)

```
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? 
What tab or screen did the error occur? 
What are the steps to reproduce the Error? 
Web link to a screenshot of your error: 
In addition to a screenshot, copy the data below and send to developer.

Source: System.Data.SQLite
Message: SQL logic error
near "FROM": syntax error
Raw Error Text: code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
near "FROM": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader()
   at EVE_Isk_per_Hour.frmMain.LoadPrices(List`1 SentItems)
   at EVE_Isk_per_Hour.frmMain.btnImportPrices_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by rsfutch77** [comment]
Ideally this would be solved by coping the user's settings from the previous version like all the other settings on this tab. 

Quick solution is to just set any default and let the user figure out that the setting was changed during the update.

**Comment by rsfutch77** [comment]
![image](https://user-images.githubusercontent.com/26337219/176980954-730ef749-e458-426b-b633-cbfdc0df5b6c.png)

Somehow ended up with a bunch of missing entries in the save file. Probably my fault when I was editing them.
