### ISSUE TITLE
Odd error.

### ISSUE THREAD

**Issue by EvE-Player** [EVEIPH/EVE-IPH#182]
``1/11/2023` 12:09:26 PM, System.OverflowException: Arithmetic operation resulted in an overflow.
   at EVE_Isk_per_Hour.ReprocessingPlant.Reprocess(Int64 ItemID, Int32 ReprocessingSkill, Int32 ReprocessingEfficiencySkill, Int32 ProcessingSkill, Double TotalQuantity, Boolean IncludeTax, BrokerFeeInfo BrokerFeeData, Double& TotalYield, Double& ReprocessingFees, Boolean MintoOreFormat, List`1& RefinedMineralsList)
   at EVE_Isk_per_Hour.frmMain.LoadMiningGrid()
   at EVE_Isk_per_Hour.frmMain.btnMineRefresh_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

---
``

Didn't cause a crash or anything, just an odd error.

**Comment by Zifrian** [comment]
If it comes up again, need a screenshot with options you selected.
