### ISSUE TITLE
SQL logic error when refreshing Blueprint Materials under Asset Viewer

### ISSUE THREAD

**Issue by mekstrem** [EVEIPH/EVE-IPH#183]
- What is your Operating System?
**Win10 Home**
- What tab or screen did the error occur? 
**Under _Asset Viewer_ -> _Selected Material Settings_**
- What are the steps to reproduce the Error?
**Click _Blueprint Materials_ then click _Refresh_ for the error to occur. (All materials selected)**
- Web link to a screenshot of your error:
https://imgur.com/a/rcMvo1r
- In addition to a screenshot, copy the data below and send to developer.

```
Source: System.Data.SQLite
Message: SQL logic error
near ")": syntax error
Raw Error Text: code = Error (1), message = System.Data.SQLite.SQLiteException (0x800007BF): SQL logic error
near ")": syntax error
   at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
   at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
   at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader()
   at EVE_Isk_per_Hour.AssetViewer.GetSearchItemsList(Boolean SearchAllItems)
   at EVE_Isk_per_Hour.AssetViewer.RefreshTree()
   at EVE_Isk_per_Hour.AssetViewer.btnSearchRefresh_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Zifrian** [comment]
This issue has been corrected in a previous patch.
