### ISSUE TITLE
Crash in Blueprint Management

### ISSUE THREAD

**Issue by EtherealWake** [EVEIPH/EVE-IPH#55]
Appear to be missing a space when building the SQL query in Blueprint Management.  This occured while clicking the 'Ignored' checkbox under 'Blueprint Filters'.

    Source: System.Data.SQLite
    Message: SQLite error
    unrecognized token: "1AND"
    Raw Error Text: System.Data.SQLite.SQLiteException (0x80004005): SQLite error
    unrecognized token: "1AND"
       at System.Data.SQLite.SQLite3.Prepare(SQLiteConnection cnn, String strSql, SQLiteStatement previous, UInt32 timeoutMS, String& strRemain)
       at System.Data.SQLite.SQLiteCommand.BuildNextCommand()
       at System.Data.SQLite.SQLiteCommand.GetStatement(Int32 index)
       at System.Data.SQLite.SQLiteDataReader.NextResult()
       at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
       at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
       at System.Data.SQLite.SQLiteCommand.ExecuteReader()
       at EVE_Isk_per_Hour.frmBlueprintManagement.UpdateBlueprintGrid(Boolean CheckAllItems)
       at EVE_Isk_per_Hour.frmBlueprintManagement.rbtnIgnored_CheckedChanged(Object sender, EventArgs e)
       at System.Windows.Forms.RadioButton.OnCheckedChanged(EventArgs e)
       at System.Windows.Forms.RadioButton.set_Checked(Boolean value)
       at System.Windows.Forms.RadioButton.OnClick(EventArgs e)
       at System.Windows.Forms.RadioButton.OnMouseUp(MouseEventArgs mevent)
       at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.ButtonBase.WndProc(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
       at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
Error Tracking:

**Comment by Zifrian** [comment]
This should be fixed. Let us know if it still crashes.

**Comment by Zifrian** [comment]
This has been fixed.
