### ISSUE TITLE
403 on login

### ISSUE THREAD

**Issue by Meigs2** [EVEIPH/EVE-IPH#85]
I'm getting a 403 error when starting up the application with an ESI character.

What is your Operating System? Windows 10 Fall Creators Update
What tab or screen did the error occur? Loading 
What are the steps to reproduce the Error? "Loading character Data from ESI"
Web link to a screenshot of your error: http://puu.sh/Av1Mk/2dcc42466a.jpg
In addition to a screenshot, copy the data below and send to developer.

```
An Unhandled Exception has occured and EVE Isk per Hour will now close.
Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: Value cannot be null.
Parameter name: value
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Value cannot be null.
Parameter name: value ---> System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at EVE_Isk_per_Hour.ESI.GetIndustryJobs(Int64 ID, SavedTokenData TokenData, ScanType JobType, DateTime& JobsCacheDate)
   at EVE_Isk_per_Hour.EVEIndustryJobs.UpdateIndustryJobs(Int64 ID, SavedTokenData CharacterTokenData, ScanType JobType)
   at EVE_Isk_per_Hour.Corporation.LoadCorporationData(Int64 CorporationID, Int64 CharacterID, SavedTokenData CharacterTokenData, Boolean RefreshAssets, Boolean RefreshBlueprints)
   at EVE_Isk_per_Hour.Character.LoadCharacterData(Int64 CharacterID, SavedTokenData& TokenData, Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Character.LoadDefaultCharacter(Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Public_Variables.LoadCharacter(Boolean RefreshAssets, Boolean RefreshBPs)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking: 
```

**Comment by Zifrian** [comment]
This should be fixed in the latest version.
