### ISSUE TITLE
Unhandled error on launch

### ISSUE THREAD

**Issue by zductiv** [EVEIPH/EVE-IPH#86]
An Unhandled Exception has occured and EVE Isk per Hour will now close.

Please fill out the following information so I can reproduce the bug

What is your Operating System? Windows 10
What tab or screen did the error occur? On launch
What are the steps to reproduce the Error? Launch after adding a character to ESI
Web link to a screenshot of your error: https://i.imgur.com/xoIEzAl.png
In addition to a screenshot, copy the data below and send to developer.

Source: EVE Isk per Hour
Message: An error occurred creating the form. See Exception.InnerException for details.  The error is: Object reference not set to an instance of an object.
Raw Error Text: System.InvalidOperationException: An error occurred creating the form. See Exception.InnerException for details.  The error is: Object reference not set to an instance of an object. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EVE_Isk_per_Hour.EVENPCStandings.UpdateCharacterStandings(Int64 ID, SavedTokenData CharacterTokenData)
   at EVE_Isk_per_Hour.EVENPCStandings.LoadCharacterStandings(Int64 CharacterID, SavedTokenData CharacterTokenData)
   at EVE_Isk_per_Hour.Character.LoadCharacterData(Int64 CharacterID, SavedTokenData& TokenData, Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Character.LoadDefaultCharacter(Boolean LoadBPs, Boolean LoadAssets)
   at EVE_Isk_per_Hour.Public_Variables.LoadCharacter(Boolean RefreshAssets, Boolean RefreshBPs)
   at EVE_Isk_per_Hour.frmMain..ctor()
   --- End of inner exception stack trace ---
   at EVE_Isk_per_Hour.My.MyProject.MyForms.Create__Instance__[T](T Instance)
   at EVE_Isk_per_Hour.My.MyProject.MyForms.get_frmMain()
   at EVE_Isk_per_Hour.My.MyApplication.OnCreateMainForm()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.OnRun()
   at Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.DoApplicationModel()
Error Tracking:

**Comment by Zifrian** [comment]
This should be fixed in the latest version.
